# Generated by Django 4.0 on 2021-12-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_modelformregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('ticket', models.TextField(blank=True, max_length=400)),
                ('position', models.PositiveIntegerField(db_index=True, unique=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
