# Generated by Django 4.0 on 2021-12-20 13:03

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chiefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('position', models.PositiveIntegerField(db_index=True, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to=base_app.models.Chiefs.get_file_name)),
                ('prof', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('position', models.PositiveIntegerField(db_index=True, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to=base_app.models.Hero.get_file_name)),
                ('showtext', models.TextField(blank=True, max_length=400)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
